// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxyBlNFWeNh9ClEEdwjea1gxEb6WQpNHo',
    appId: '1:370649059263:web:3a3c9e78b85544e1bfdb0a',
    messagingSenderId: '370649059263',
    projectId: 'app-emi-d2bf6',
    authDomain: 'app-emi-d2bf6.firebaseapp.com',
    storageBucket: 'app-emi-d2bf6.appspot.com',
    measurementId: 'G-JDGBCQ9WTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCup7lVndGaSYgkdx9F_nTWrgIEnW-zHuY',
    appId: '1:370649059263:android:056e79b6aa7ab04cbfdb0a',
    messagingSenderId: '370649059263',
    projectId: 'app-emi-d2bf6',
    storageBucket: 'app-emi-d2bf6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk-xOhqngZ1u5yHqdymsZJM_jhX0dO0TQ',
    appId: '1:370649059263:ios:293230f47ddd4fb2bfdb0a',
    messagingSenderId: '370649059263',
    projectId: 'app-emi-d2bf6',
    storageBucket: 'app-emi-d2bf6.appspot.com',
    iosClientId: '370649059263-iih60ce10e6p34g1g89v6t3gpcpl04te.apps.googleusercontent.com',
    iosBundleId: 'com.example.appEmi',
  );
}
